### ISSUE TITLE
Mejores

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-conchaasensiomr#1]
Buen trabajo @conchaasensiomr !

### Algunas pistas para acabarlo:

- [x] Usa el `id` de cada pokemon en el `li` para el `key` de react cuando mapeas y creas un listado de componentes
- [x] El segundo parámetro de un map es un index, no un id. Te recomiendo cambiar el nombre de ese parámetro para que no lleve a confusión.
- [x] Elimina el código comentado, debuggers y consoles
- [x] Usa propTypes para comprobar el tipo de dato de las props

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by conchaasensiomr** [comment]
¡Gracias, Miguel! Me pongo con ello ;)
